site_name: simpleorm


site_url: https://yourproject.readthedocs.io

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md


markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - def_list
  - pymdownx.superfences